### ISSUE TITLE
希望能及早添加分辨率切换功能

### ISSUE THREAD

**Issue by zzsdsgdtc** [Paladinfeng/MiaoProject#10]
似乎默认会使用可用的最高分辨率？4k分辨率100%出现间断性卡顿，不知道是不是我的网络带宽不够(400Mbps)。现在有越来越多的视频有4k分辨率了，实在影响观看体验。

**Comment by Paladinfeng** [comment]
什么型号的设备啊？目前我本地测试，绝大多数的4K视频是可以正常播的

**Comment by zzsdsgdtc** [comment]
A1842 tvOS 14.5

**Comment by zzsdsgdtc** [comment]
卡顿我是指播放暂停，看起来是在加载，不是画面异样。所以我觉得应该是我的网的问题。 我用apple tv 连接的是非4k的投影仪，所以其实并用不到4k分辨率。

**Comment by zzsdsgdtc** [comment]
我只是upvote一下这项功能，希望能考虑赋予此项功能更高开发priority ;)

**Comment by Steve-luo** [comment]
应该还是CDN的问题。我在美国，PC端播放短一点的4K视频可以正常看完，稍微长一点的比如20多分钟的4K经常看到一大半就开始卡，缓存速度起不来，只能切到1080P高码率把视频看完。

**Comment by Paladinfeng** [comment]
目前播放用的B站的旧接口，所以应该存在国外CDN的问题，国内的播放效果还好，切换分辨率的功能我是设计在播放器面板上的，这块儿功能还没开始写

**Comment by wisesimpson** [comment]
我也遇到了类似的问题，在国外看4K要加载很长时间而且播放一段还会卡顿。关于如何实现我有两个想法：
- 简化的方法是在设置中增加一项“优先加载的分辨率”，这样就避免在播放器界面增加更多的操作。
- 播放器使用“auto”分辨率，如果卡顿就自动降低分辨率，类似Netflix的解决方法，同样也避免了给播放器增加选项。

ps：感谢 @Paladinfeng 的工作，整体来说非常棒！

**Comment by Paladinfeng** [comment]
开始根本没想到国外看B站的用户，目前正在搞第二种方案

**Comment by zzsdsgdtc** [comment]
我感觉国外用户应该相当多的吧。我其实挺好奇的，国内能用apple tv嘛？netflix之类的不需要个梯子嘛？我一开始以为 @Paladinfeng 你也在国外呢

**Comment by avsba001** [comment]
国内用户默默冒个泡，

**Comment by Paladinfeng** [comment]
原生播放器和动态分辨率不好搞，先更新了一般「首选分辨率」的设置
