### ISSUE TITLE
特定视频会造成闪退

### ISSUE THREAD

**Issue by xxxbrian** [Paladinfeng/MiaoProject#101]
**MiaoProject build:** 1.0 (55)
**tvOS:** 15.2 (19K53)
**Model:** A2169

[【⚡“再下去要输越南了”⚡】- 哔哩哔哩](https://www.bilibili.com/video/BV1p3411E7bi) 
**播放视频时会发生闪退。**

**Comment by Paladinfeng** [comment]
感谢反馈
经过测试，未能复现该问题，开发者后台也没能看到相关的崩溃日志

**Comment by Paladinfeng** [comment]
大概知道是啥问题了，预计下版本修复
