### ISSUE TITLE
希望能让追剧体验更好一些

### ISSUE THREAD

**Issue by yxlimo** [Paladinfeng/MiaoProject#103]
目前追剧的入口是 番剧 -> 查看全部 -> 追剧

入口有点深

参考某 box 的界面

![image](https://user-images.githubusercontent.com/13878887/152636612-93059780-577c-452a-9bd1-0942d6c94b59.png)

**Comment by Paladinfeng** [comment]
之后会优化一下，但是不会添加到Tab里

**Comment by Paladinfeng** [comment]
追剧已添加新入口
