### ISSUE TITLE
部分4k视频音量小

### ISSUE THREAD

**Issue by GiovanniVDW** [Paladinfeng/MiaoProject#106]
近期发现部分4k视频使用Miao播放声音很小，如下面例子：

4k: https://b23.tv/ZU4cQf2
1080p: https://b23.tv/1DK8ki4

ios客户端/apple tv网页浏览器，观看两个视频音量基本一致。

麻烦大佬帮忙看下是什么问题，辛苦了

**Comment by Paladinfeng** [comment]
我本地无论是连接HomePod还是直接电视发声，都没有发现音量问题
如果你的电视支持「音量平衡」可以打开试试
