### ISSUE TITLE
建议增加“稍后再看”及字幕默认 on 功能

### ISSUE THREAD

**Issue by urniar** [Paladinfeng/MiaoProject#107]
rt
现在收藏按钮还要跳出是否选用默认收藏夹，建议加个稍后再看按钮；
同时cc 字幕现在是默认 off，建议默认 on 或者设置内可选全局应用，不用每个视频单独选
谢谢

**Comment by Paladinfeng** [comment]
1. 收藏选择文件夹的逻辑并没有什么问题，因为用户可以创建多个收藏夹
2. 添加稍后再看目前不会做
3. CC字幕的设置，和你在系统中设置的字幕语言偏好有关，也和你上次选择的字幕有关，我这边有中文简体字幕，是可以自动加载出来的
