### ISSUE TITLE
掉帧情况。

### ISSUE THREAD

**Issue by kamenriderzxt** [Paladinfeng/MiaoProject#109]
我的是小米电视，分辨率1080的，软件在可以自己选择分辨率版本的时候没有掉帧，我不知道什么时候自动更新到了自动分辨率版本，大概是过年前，更新后看着看着有掉帧的情况，暂停再播放可以解决一会儿。尝试过设置里的各种关于视频播放的设置，什么仅加载最高分辨率之类的选项，怎么调试都没用，看着看着就会掉帧，需要暂停再播放，过一会儿又掉帧，又要再来一次。表示很难受。有大会员。

**Comment by kamenriderzxt** [comment]
电视：小米4X  1080P
盒子：Apple TV 4k 2017
系统：15.3
MiaoProjwct：1.0  B57

**Comment by kamenriderzxt** [comment]
电视：小米4X 1080P
盒子：Apple TV 4k 2017
系统：15.3
MiaoProject：1.0 B57

**Comment by kamenriderzxt** [comment]
【关于apple tv掉帧后暂停恢复问题。-哔哩哔哩】 https://b23.tv/qzc3oRD

视频已上传。

**Comment by xjiangiao** [comment]
我也遇到了掉帧的问题，Apple TV 4k 2017版，小米电视大师65跟视频情况类似，2021版Apple TV 4k搭配索尼a80j无此问题。

**Comment by Paladinfeng** [comment]
Build 63 更新了一个设置 -「过滤超过60帧的视频」，卡顿掉帧的，试一下开启之后还有没有问题
- 新增：设置 -「过滤超过60帧的视频」，开启后可能会改善某些视频丢帧导致无法正常观看的问题，请仔细阅读说明和副作用，仅建议有此问题的用户自行尝试
