### ISSUE TITLE
单声道视频以及5.1环绕声系统播放声道不匹配

### ISSUE THREAD

**Issue by Steve-luo** [Paladinfeng/MiaoProject#11]
我的ATV配了一套5.1系统，Miao播放双声道视频的时候左声道确实是从左声道出来的，但是右声道的声音是从中央声道出来的，播放单声道视频的时候就只有左声道在响，导致总体听感偏左，希望能修复下。

设置强制双声道之后双声道视频正常播放，单声道视频还是只有左声道在响。

单声道的问题可以加个急修修，5.1毕竟比较小众，优先级可以稍低点。

**Comment by Paladinfeng** [comment]
目前项目采用的是第三方播放器，立体声的问题我提上去挺久了，并没有得到回复
相关issue: https://github.com/kingslay/KSPlayer/issues/156

**Comment by Steve-luo** [comment]
了解，那就等等播放器的修复吧。

**Comment by Paladinfeng** [comment]
请更新到 Build 10 之后，再试一下
