### ISSUE TITLE
建议增加类似androidtv那样的投屏功能

### ISSUE THREAD

**Issue by jcc563768606** [Paladinfeng/MiaoProject#111]
类似androidtv那样，能在一个局域网下识别到播放设备就行，不知道能不能实现，可能需要硬件支持？

**Comment by jcc563768606** [comment]
为什么不用apple生态的那个airdrop呢，是因为：
1.airdrop在用ipad给tv投屏的时候弹幕的字号不能很好适应，在atv上特别小
2.一旦用atv的airdrop播放一个视频之后，就不能退出当前页面，不然atv也会暂停，没有安卓tv那么舒服

**Comment by Paladinfeng** [comment]
这只是一个第三方客户端，做不到一些官方的功能
