### ISSUE TITLE
关于增加倍速速率的建议

### ISSUE THREAD

**Issue by Eleveven** [Paladinfeng/MiaoProject#112]
rt 
我是有这样一个场景：我经常使用B站看视频学习，部分视频的内容节奏较慢，所以有倍速看视频的习惯。
当前所支持的倍速有1x/1.25x/1.5x，可否开放更高的速率。比如B站原生的2x或者2+。望采纳。谢谢。

**Comment by Paladinfeng** [comment]
二倍速大概率会导致某些高帧率视频丢帧，所以解决之前不会增加二倍速及以上
