### ISSUE TITLE
播放视频黑屏 显示错误

### ISSUE THREAD

**Issue by sage9o** [Paladinfeng/MiaoProject#113]
用手机和电脑播放bilibili视频正常
用obox也能正常播放b站视频
但是用了miao 就显示黑屏 一直转圈 最后报错 
不过设置国外节点却能正常播放...
不知道是什么原因 求助

**Comment by Paladinfeng** [comment]
应该是你的网络分流的问题，估计你用的是白名单，pcdn服务海外无法连接，导致一直loading
1. 连接手机热点测试能否正常播放
2. 调试你自己的分流策略
