### ISSUE TITLE
视频列表中选中位置变化

### ISSUE THREAD

**Issue by littlepanda0716** [Paladinfeng/MiaoProject#114]
在视频列表中，每次下滑至需要加在更多视频内容时，当前选中视频都会从最后一行调回至当前页面显示的视频中第一行第一个

**Comment by littlepanda0716** [comment]
> 我tvos升到15.4以后也有这个问题

升级到15.4之后遇到的 +1

**Comment by Paladinfeng** [comment]
15.4下确实会有这个问题，我会想办法修复的

**Comment by Paladinfeng** [comment]
Build 63 已修复
