### ISSUE TITLE
怎么回事？miaoproject打开要求输入SMB地址信息？

### ISSUE THREAD

**Issue by leslie111666** [Paladinfeng/MiaoProject#118]
今天像往常一样打开miaoproject，直接就变成图示情况，不知道是怎么了？望解惑
![QQ图片20220403161126](https://user-images.githubusercontent.com/102897091/161418542-9581320f-93f8-4e96-ae60-7cdfda197f2d.jpg)
。

**Comment by Paladinfeng** [comment]
能不能看看更新日志？

**Comment by leslie111666** [comment]
谢谢

**Comment by sliencex** [comment]
我也是这个问题，直接被作者关掉了。

**Comment by sliencex** [comment]
激活方法

选择远程连接
点击第一个输入框（请输入播放资源链接）
输入 miao://platform/show
重新启动应用
