### ISSUE TITLE
为什么今天一早打开App发现进去了一个类似连接SMB的服务的界面，不能用了。

### ISSUE THREAD

**Issue by sliencex** [Paladinfeng/MiaoProject#119]

**Comment by Paladinfeng** [comment]
我不知道你第一次的时候是怎么用的，现在去看一下激活说明

**Comment by sliencex** [comment]
![image](https://user-images.githubusercontent.com/74479287/161421495-b281f84b-eb28-477e-8366-43598708fd2d.png)

**Comment by sliencex** [comment]
原来都是好的，今天一早打开就变成这样了，你昨天是不是做了一个更新？我看有效期又是90天了。

**Comment by Paladinfeng** [comment]
你能不能看一下更新日志和使用说明啊

https://github.com/Paladinfeng/MiaoProject/blob/master/Changelog.md
https://github.com/Paladinfeng/MiaoProject/blob/master/HOW-TO-USE.md

**Comment by sliencex** [comment]
懂了懂了，在远程连接里面输入miao://platform/show搞定了，多谢，不好意思啊。打扰你休息。

**Comment by sliencex** [comment]
激活方法

选择远程连接
点击第一个输入框（请输入播放资源链接）
输入 miao://platform/show
重新启动应用
