### ISSUE TITLE
视频倍速bug

### ISSUE THREAD

**Issue by YingcaiDong** [Paladinfeng/MiaoProject#133]
按照如下方法即可复现bug

1. 播放视频，选择一个倍速（比如x1.5倍速），点击暂停，然后播放。视频倍速消失（恢复为x1.0）
2. 播放视频，选择一个倍速（比如1.25）。退出视频在进入。视频速度还原为1.0，但是倍速选项依然勾选为退出前的倍速。

**Comment by Paladinfeng** [comment]
已修复
