### ISSUE TITLE
视频倍速后返回按钮逻辑bug

### ISSUE THREAD

**Issue by YingcaiDong** [Paladinfeng/MiaoProject#134]
正常情况下
1. 当显示进度条时点击遥控器返回按钮会隐藏进度条。
2. 点击【弹幕】，【字幕】，【音轨】按钮后，点击一次遥控器返回按钮会移除上述按钮的选择状态，第二次点击返回按钮会隐藏进度条。

bug复现：
1. 点击【倍速】按钮
2. 选择一个倍速（如1.5）。
3. 点击一次返回按钮（会看到移除倍速按钮高亮被移除）
4. 第二次点击返回按钮，bug出现，视频将会退出，而不是隐藏进度条。

**Comment by Paladinfeng** [comment]
这个还真是系统播放器的锅，如果你用tv+试一下，应该也是同样的问题
所以每次到进度条，我都等它自动消失

**Comment by YingcaiDong** [comment]
哈哈好的！
