### ISSUE TITLE
atv6新版遥控器不适配的问题

### ISSUE THREAD

**Issue by SIMPO18** [Paladinfeng/MiaoProject#14]
在播放界面新的遥控器的滚轮区域完全没作用，方向键和确定键按下毫无反应，向下轻扫滑动也没作用，目前在播放界面只能使用播放暂停键。

**Comment by ZhxChen** [comment]
同样问题

**Comment by nollaG** [comment]
同样问题，希望作者可以fix

**Comment by Paladinfeng** [comment]
目前还在测试原生播放器，如果没问题，就可以适配新遥控器了

现在只支持播放 / 暂停 / 快进

**Comment by Paladinfeng** [comment]
Duplicate of #4
