### ISSUE TITLE
部分视频 在hdr电视上 播放一段时间后逐渐卡顿

### ISSUE THREAD

**Issue by CyEilo** [Paladinfeng/MiaoProject#140]
最新版本（68）
1.
atv 设置 4k杜比视界 匹配动态范围 匹配帧速率
播放部分视频 一分钟左右会慢慢变卡 
此时轻触遥控器调出播放进度条就会正常 
进度条消失后一段时间又会出现卡顿（仅视频卡顿 弹幕不会 音画是同步的 只是画面出现类似掉帧的情况）
[如果关闭atv的 匹配动态范围 就没有这个问题]
另一个投影仪 设置的是4k sdr 关闭匹配动态范围 关闭匹配帧速率 就不会出现这个问题
测试视频1：https://www.bilibili.com/video/BV12R4y1A7XF
测试视频2：https://www.bilibili.com/video/BV1Z34y1h7at

2.
还有另外一个直播相关的问题，不知道有没有关联
部分主播的直播间会出现音画不同步 表现为视频偶尔卡顿然后慢慢落后于音频，时间长了会非常明显 按下暂停后 声音会停止 画面会继续播放直到和音频暂停的地方同步
因为直播看得不多 目前只发现 
翼侯大人 会有这个情况 （直播本来看得不多）
https://live.bilibili.com/60989?broadcast_type=0&visit_id=9pqhnnezl7w0

3.
打开直播 经常加载失败 要尝试很多次才能打开一次

2，3 没有仔细尝试过看是什么问题导致的

**Comment by Paladinfeng** [comment]
Q1： 打开设置里的过滤六十帧视频的选项
Q2&Q3：直播会在之后的版本更新接口
