### ISSUE TITLE
番剧解析出错

### ISSUE THREAD

**Issue by sliencex** [Paladinfeng/MiaoProject#143]
一早更新后番剧解析出错

**Comment by Paladinfeng** [comment]
报错信息是什么？

**Comment by sliencex** [comment]
![image](https://user-images.githubusercontent.com/74479287/171980350-13c999e9-4c00-4194-bb68-aa2e0359d4b9.png)

**Comment by Paladinfeng** [comment]
已经更新修好了

**Comment by sliencex** [comment]
是的，你好神速。。。

**Comment by Paladinfeng** [comment]
因为群里也有人反馈了这个问题

感谢反馈
