### ISSUE TITLE
观看视频时，提示此服务器的证书无效

### ISSUE THREAD

**Issue by github-szhang** [Paladinfeng/MiaoProject#149]
关注的多个up主的视频播放时提示，此服务器的证书无效，目前约有1/2到3/4的视频是这样。
![Uploading C7C12630-C0B8-48B0-81EB-EFC8F0942265.jpeg…]()

**Comment by Paladinfeng** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/15520106/174486258-3d0f085c-6964-4506-ae8f-8495e68f60e0.png">
SSL证书过期了，等修复吧

**Comment by github-szhang** [comment]
感谢回复，一度以为是盒子坏了，一部分能看一部分不行，PC端又都可以。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZFXUE ***@***.***&gt;
发送时间: 2022年6月19日 22:35
收件人: Paladinfeng/MiaoProject ***@***.***&gt;
抄送: s.zhang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Paladinfeng/MiaoProject] 观看视频时，提示此服务器的证书无效 (Issue #149)





 

 SSL证书过期了，等修复吧

**Comment by Paladinfeng** [comment]
应该已经修好了

**Comment by github-szhang** [comment]
测试了几个视频，确实好了，感谢大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZFXUE ***@***.***&gt;
发送时间: 2022年6月20日 00:16
收件人: Paladinfeng/MiaoProject ***@***.***&gt;
抄送: s.zhang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Paladinfeng/MiaoProject] 观看视频时，提示此服务器的证书无效 (Issue #149)






应该已经修好了
