### ISSUE TITLE
输入链接、重启APP后无效

### ISSUE THREAD

**Issue by mjxoicq** [Paladinfeng/MiaoProject#151]
你好，我的Apple tv 2021安装miao、输入链接、重启app后没有任何变化，请问应该如何处理？感谢

**Comment by Paladinfeng** [comment]
机制是没问题的
你确认下自己输入对不对，大小写，中间是否有空格
如果是 tvOS 15 的话，目前需要手动输入，复制粘贴是不触发的
还是不行的话，拍一下你输入的内容看一下

**Comment by mjxoicq** [comment]
突然又好了，不知道是什么问题。当时不管复制、手输都没用，试了10次左右。不过现在没问题了，我先再观察下。感谢
