### ISSUE TITLE
播放影片提示“未知错误 无法完成操作”

### ISSUE THREAD

**Issue by ichaobuster** [Paladinfeng/MiaoProject#155]
纪录片[《谎言的真相》](https://www.bilibili.com/bangumi/play/ep122704)能稳定重现这个问题。

**Comment by Paladinfeng** [comment]
查到了，这部是老番，没有重新压制，只有flv格式，这个格式不支持，无法播放
<img width="419" alt="image" src="https://user-images.githubusercontent.com/15520106/184478065-6a96f3f0-d84e-4f01-b251-4e07d06ad40c.png">
