### ISSUE TITLE
支持下追番追剧相关功能？

### ISSUE THREAD

**Issue by yxlimo** [Paladinfeng/MiaoProject#17]
现在没有追番追剧的入口，曲线救国放到收藏夹里也不显示

**Comment by yxlimo** [comment]
顺便问下我现在开始学 swift 还来得及贡献 pr 吗 :)

**Comment by Paladinfeng** [comment]
追番功能有开发计划的，收藏夹的问题我查了一下，发现是接口更新了

学Swift当然没问题，不过现在项目没准备开源
