### ISSUE TITLE
动态不能刷新

### ISSUE THREAD

**Issue by kevin949373048** [Paladinfeng/MiaoProject#18]
动态不能刷新

**Comment by Paladinfeng** [comment]
请仔细阅读使用说明 
https://github.com/Paladinfeng/MiaoProject/blob/master/HOW-TO-USE.md

**Comment by kevin949373048** [comment]
> 不能刷新是说报错还是你不知道刷新方法？
> 
> 请仔细阅读使用说明
> https://github.com/Paladinfeng/MiaoProject/blob/master/HOW-TO-USE.md

动态可以按开始关闭刷新 其他都不行 都停留在登陆那一天

**Comment by kevin949373048** [comment]
> 不能刷新是说报错还是你不知道刷新方法？
> 
> 请仔细阅读使用说明
> https://github.com/Paladinfeng/MiaoProject/blob/master/HOW-TO-USE.md

好了 应该是我不太会用
