### ISSUE TITLE
播放器输出分辨率问题

### ISSUE THREAD

**Issue by TeemoWuu** [Paladinfeng/MiaoProject#184]
miaoproject在播放视频时，会根据视频质量，调整视频输出，如视频是4K 24P，则miaoproject就会将电视的输出信号进行调整。在调整过程中，我的电视会暂时黑屏去接收新信号。

对比youtube TV客户端，无论什么质量的视频，都是4K 60P输出信号，仅是针对HDR视频会重新调整输出信号，miaoproject可以完成这个修改吗？

**Comment by Paladinfeng** [comment]
不想开就在miao的设置里边关掉

**Comment by Paladinfeng** [comment]
除了动态范围，帧数也会重新匹配

https://support.apple.com/en-hk/HT208288
