### ISSUE TITLE
可以在美区上架吗

### ISSUE THREAD

**Issue by dickwu** [Paladinfeng/MiaoProject#185]
因为使用的是美区账号不方便切换，能否可以在美区上架呢

**Comment by NyaDoo** [comment]
同求上架

**Comment by Theal1** [comment]
同求上架

**Comment by jun4rui** [comment]
同求

**Comment by Paladinfeng** [comment]
https://paladinfeng.notion.site/140462eaa3134ff68909102cb2b37e32

**Comment by GS-Echo** [comment]
日，刚好错过。。。

**Comment by GS-Echo** [comment]
日，刚好错过。。。上架有地方能看到通知吗？

**Comment by GS-Echo** [comment]
> 日，刚好错过。。。上架有地方能看到通知吗？

没事了，之前telegram不会用，群没加进去
