### ISSUE TITLE
所有功能无法使用，报错：数据解析错误或者网络请求错误，已尝试删除软件重装和强制清楚登录信息

### ISSUE THREAD

**Issue by raiuka** [Paladinfeng/MiaoProject#189]
有一段时间没用了，今天发现图标更新了，打开试试发现所有的分项都是用不了的，有的是网络请求错误，有的是数据解析错误，有的是未知错误。

已尝试：删除软件重新安装，强制重新登录，清除登录信息，全部无效。
![19EAE247-FE32-4CA1-BF66-71F19DAEA34B](https://user-images.githubusercontent.com/53719018/222960956-15924708-9887-4ebc-bc91-679c1ff0e188.jpeg)

![EBF1079E-D6AA-49E9-BCC0-0810C650A886](https://user-images.githubusercontent.com/53719018/222960964-07860096-41df-47ef-854a-203315abb4c0.jpeg)

![EC0DBE7F-3D92-4ABF-A29E-B2213C1795F0](https://user-images.githubusercontent.com/53719018/222960973-bbaec831-d205-4736-9fbe-7eaffde9c65a.jpeg)

![D4E8403D-84FF-4490-AEC6-297B227F22AC](https://user-images.githubusercontent.com/53719018/222960984-46bb9fcf-fa44-46ff-990b-2876fcf12e1b.jpeg)

**Comment by Paladinfeng** [comment]
B站崩了，看微博热搜
