### ISSUE TITLE
期待加入缓存体积查看和清空缓存功能

### ISSUE THREAD

**Issue by Theal1** [Paladinfeng/MiaoProject#200]
【期望】
1、在MiaoProject中可以实时查看缓存体积，并且可以手动清空视频缓存、封面等占用体积较大的内容（登录信息应该占用空间极小，没必要一起清除）；

2、如果可以增加“达到XX GB自动清除缓存”的选项，XX可选“5、10、20、40”等数值，则更方便。

【背景】
1、Apple TV 4K 二代，64G，只安装了MiaoProject和infuse Pro 7，使用一段时间后频繁出现infuse提示“磁盘空间不足、元数据缓存已清除”。把infuse的缓存方式改为传统或仅内存也是一样。而且在infuse设置中查看缓存用量一般也就1GB；

2、即使刚被清除infuse缓存，用Xcode连接ATV显示Capacity 53.63GB，available也仅有1.23GB ，并没有解决问题。但我把系统屏保都设置为图片而非4K视频了，依然剩余空间不足、频繁出现infuse缓存被清的情况。不知道问题出在哪里；

3、现在已经还原ATV到出厂，重新安装并设置了MiaoProject和infuse，目前50.06GB available，infuse缓存1.0GB。再观察一段时间看看。
-----
MiaoProject做得真心棒，谢谢作者的辛苦付出！

**Comment by Paladinfeng** [comment]
收到反馈，感谢使用，Miao 目前只会缓存封面图片，限制最大缓存256MB，过期时间7天
`ImageCache.default.diskStorage.config.sizeLimit = 256 * 1024 * 1024`

日后会更新清理缓存的功能

PS：tvOS 17 应该是更新了查看每个App占用多少硬盘容量的功能，可能等正式版更新

**Comment by Theal1** [comment]
> 收到反馈，感谢使用，Miao 目前只会缓存封面图片，限制最大缓存256MB，过期时间7天 `ImageCache.default.diskStorage.config.sizeLimit = 256 * 1024 * 1024`
> 
> 日后会更新清理缓存的功能，我也会继续观察 Miao 的占用情况
> 
> PS：tvOS 17 应该是更新了查看每个App占用多少硬盘容量的功能，可能等正式版更新

原来如此，感谢您的回复。
期待tvOS 17更新，应该就能知道问题所在了~~
