### ISSUE TITLE
向下滚动视频列表，加载新内容时，焦点回到当前页面左上角

### ISSUE THREAD

**Issue by haoyu1999** [Paladinfeng/MiaoProject#203]
在首页视频列表向下浏览时，遇到需要继续加载下一页的时候，整个页面会闪烁，同时焦点回到当前页面第一行第一个视频。现象同 #114。

系统版本：tvOS 15.5.1
软件版本：从App Store下载并更新，不记得版本了，记得之前App图标是一只猫的时候没有此问题，更新后App图标变化，出现了此问题。

**Comment by Paladinfeng** [comment]
你不准备更新到最新系统吗？

之前是部份刷新，现在改为了全局刷新

**Comment by haoyu1999** [comment]
是的，由于担心更新系统过程中一旦出现问题没法自己解决，会导致一家人无法看电视，所以不打算更新系统。

App 版本是 2.2.0，今天刚更新的，上一个版本也有此问题。

**Comment by haoyu1999** [comment]
升级到 tvOS 16.6 解决了此问题。
