### ISSUE TITLE
调整视频倍速，暂停后恢复播放，播放速度变回 1.0x

### ISSUE THREAD

**Issue by haoyu1999** [Paladinfeng/MiaoProject#204]
播放任意视频，在菜单中选取倍速（如 1.5x），然后暂停，再恢复播放。发现视频以正常速度播放，而非选择的倍速播放。但倍速菜单中仍然勾选的是之前选取的倍速。

系统版本：tvOS 15.5.1
软件版本：2.2.0 （上一个版本无此问题）

**Comment by Paladinfeng** [comment]
2.2.1 更新会修复
