### ISSUE TITLE
tvOS 17.2 beta 4 会闪退

### ISSUE THREAD

**Issue by cgao35** [Paladinfeng/MiaoProject#212]
打开后就直接关闭，画面甚至不会进入到miao的页面。
建议暂时关闭 tvOS beta，至少跳过目前的 beta 4。

不知 beta 5 （或者 17.2 RC？）会不会修复这个问题，如果持续的话，miao 这边会有什么对策吗？

**Comment by Paladinfeng** [comment]
这种问题一般都是beta系统导致的，可能下一个beta版本就好了
除非是开发者，否则不建议一直停留在beta系统版本
如果闪退出现在正式版中，一定会第一时间修复

**Comment by Paladinfeng** [comment]
确认为beta 4系统bug，已经提交了demo和issue给苹果

友情提示：普通用户不要一直停留在beta系统版本

**Comment by Paladinfeng** [comment]
> 新版beta没修，芜湖

正在手动修复，预计这两天搞定

**Comment by Paladinfeng** [comment]
2.2.6 已更新，绕开了导致闪退的方法

**Comment by CharlesGBLee** [comment]
谢谢，已经更新
