### ISSUE TITLE
打开视频或直播时，出现 URLSessionTask failed 或者 SSL 错误

### ISSUE THREAD

**Issue by chshouyu** [Paladinfeng/MiaoProject#215]
最近一段时间出现了这两个错误弹窗
由于弹窗消失太快来不及捕捉

重试可解决，不影响正常使用，只是有点烦人

**Comment by Paladinfeng** [comment]
1. 请确定 App 更新到了最新版本，建议打开 App 自动更新
2. 请测试一下本地网络，如果连接了软路由或者代理工具，请尝试直连网络
3. 我当前的网络环境下没有出现过该情况
4. 如果重试正常，也可能存在 API 限制，如果可能，请提供一下具体的报错信息

**Comment by chshouyu** [comment]
待我再观察一段时间看看

**Comment by chshouyu** [comment]
尝试录屏了 15 分钟，打开关闭几十个视频没有复现，但是不录屏的时候又能复现，蛋疼
具体的错误信息大概是：“URLSessionTask failed with SSL error，无法与服务器建立安全链接”
确实使用了软路由，但 geosite:bilibili 已配置直连规则
如果无法稳定复现，恐怕 debug 也很困难
可以等待其他用户反馈

**Comment by chshouyu** [comment]
终于捕捉到了

https://github.com/Paladinfeng/MiaoProject/assets/1304342/2234428d-a707-4a0f-b35e-fce20d3702f5


https://github.com/Paladinfeng/MiaoProject/assets/1304342/1f454e5b-7e6a-4391-b081-48481a53c08c

**Comment by Paladinfeng** [comment]
麻烦关掉代理工具后，再测试一下，直连规则不一定可信

**Comment by chshouyu** [comment]
可以确定是 openwrt 各种插件导致的问题

**Comment by chshouyu** [comment]
折腾了两个月，终于知道问题出在哪里了，简单来说就是宽带 ipv6 的问题
如果代理插件的 DNS 会返回 ipv6 地址，但是路由器关闭了 ipv6 功能，就会导致域名和 IP 对应不上，就会报 SSL 错误
解决方式有两个：

1. 完全关闭 ipv6 功能，包括路由器设置以及代理插件 DNS 设置
2. 完全开启 ipv6 功能，同上

总之不要出现域名和 IP 匹配不上的问题

**Comment by Paladinfeng** [comment]
感谢尝试与反馈
