### ISSUE TITLE
b站动态无法刷新

### ISSUE THREAD

**Issue by xairt** [Paladinfeng/MiaoProject#216]
![IMG_3192](https://github.com/Paladinfeng/MiaoProject/assets/28391570/0fe223db-2624-43a2-bd0e-83c94ed4b8d3)
如标题所述，b站刷新动态时会报错。

我试过退出从新登录也没有解决，我家两台apple tv都是tvos17.4，均报错……

**Comment by chshouyu** [comment]
嘿，我也捕捉到了

![miao-error-message-0001](https://github.com/Paladinfeng/MiaoProject/assets/1304342/b58f4521-5bd1-4ed8-b9f7-6c04dbef4eff)

**Comment by qiaqiaxian** [comment]
同样错误
![IMG_5835](https://github.com/Paladinfeng/MiaoProject/assets/21219815/1073d42b-a0ff-4851-ae10-16b27645f687)

**Comment by chshouyu** [comment]
@qiaqiaxian 索尼什么型号？

**Comment by Paladinfeng** [comment]
已修复，需要更新 App 到 2.2.11

更新方法：打开 TV App Store / 搜索 miao / 点击更新
