### ISSUE TITLE
Build 10无法播放视频

### ISSUE THREAD

**Issue by zzc941210** [Paladinfeng/MiaoProject#22]
刚刚升级了build10，点击播放以后会闪退，试了很多个视频都一样，用testflight降级到build9以后就恢复正常了。

硬件是A2169。系统14.6。不知道还有什么有用的信息可以提供。

**Comment by Paladinfeng** [comment]
麻烦更新到 Build 11 再试一下，应该已经修复了

**Comment by zzc941210** [comment]
成功了！非常感谢！
