### ISSUE TITLE
apple tv 版本无法刷新出稍后在看和播放历史记录

### ISSUE THREAD

**Issue by wjzeng** [Paladinfeng/MiaoProject#220]
从2024.0702 中午开始，apple tv 版本无法刷新出稍后在看和播放历史记录。

**Comment by wjzeng** [comment]
报错，刷新token失败。

**Comment by Paladinfeng** [comment]
请尝试清空登录信息后，重新登录

**Comment by wjzeng** [comment]
使用退出和强制退出，再扫码登陆都无法解决。

**Comment by wjzeng** [comment]
清空登陆信息后问题依旧。
历史记录，我的收藏和稍候再看这三项都无法看到内容。

**Comment by Paladinfeng** [comment]
App 有更新吗？昨天B站服务器崩了，现在测试着已经正常了啊

**Comment by wjzeng** [comment]
> App 有更新吗？昨天B站服务器崩了，现在测试着已经正常了啊

版本是20240527.
昨天b站出问题是所有视频都播放不了.后来恢复后大部分吧功能正常了，但我刚才说的3个功能还是有问题，且持续到现在.

**Comment by wjzeng** [comment]
> App 有更新吗？昨天B站服务器崩了，现在测试着已经正常了啊

之前在”稍后再看“那里刷新也会报token的错误，但数据能出来，这次是完全没数据了.

**Comment by Paladinfeng** [comment]
> > App 有更新吗？昨天B站服务器崩了，现在测试着已经正常了啊
> 
> 版本是20240527. 昨天b站出问题是所有视频都播放不了.后来恢复后大部分吧功能正常了，但我刚才说的3个功能还是有问题，且持续到现在.

刚测试过这三个功能，我这边都是正常的，方便进群私聊我一下吗？https://t.me/miaoproject

**Comment by wjzeng** [comment]
> > > App 有更新吗？昨天B站服务器崩了，现在测试着已经正常了啊
> > 
> > 
> > 版本是20240527. 昨天b站出问题是所有视频都播放不了.后来恢复后大部分吧功能正常了，但我刚才说的3个功能还是有问题，且持续到现在.
> 
> 刚测试过这三个功能，我这边都是正常的，方便进群私聊我一下吗？https://t.me/miaoproject

你好，还有别的交流渠道么，我国内手机号注册不了这个的账号，搞起来很麻烦。

**Comment by Paladinfeng** [comment]
> > > > App 有更新吗？昨天B站服务器崩了，现在测试着已经正常了啊
> > > 
> > > 
> > > 版本是20240527. 昨天b站出问题是所有视频都播放不了.后来恢复后大部分吧功能正常了，但我刚才说的3个功能还是有问题，且持续到现在.
> > 
> > 
> > 刚测试过这三个功能，我这边都是正常的，方便进群私聊我一下吗？https://t.me/miaoproject
> 
> 你好，还有别的交流渠道么，国内手机号注册不了这个的账号，搞起来很麻烦。

Discord 加我好友也行，直接搜索用户 paladinfeng

<img width="1084" alt="image" src="https://github.com/Paladinfeng/MiaoProject/assets/15520106/9a15911d-efd8-46b0-ab11-2ab8935f827c">

**Comment by wjzeng** [comment]
> > > > > App 有更新吗？昨天B站服务器崩了，现在测试着已经正常了啊
> 
> > > > 
> 
> > > > 
> 
> > > > 版本是20240527. 昨天b站出问题是所有视频都播放不了.后来恢复后大部分吧功能正常了，但我刚才说的3个功能还是有问题，且持续到现在.
> 
> > > 
> 
> > > 
> 
> > > 刚测试过这三个功能，我这边都是正常的，方便进群私聊我一下吗？https://t.me/miaoproject
> 
> > 
> 
> > 你好，还有别的交流渠道么，国内手机号注册不了这个的账号，搞起来很麻烦。
> 
> 
> 
> Discord 加我好友也行，直接搜索用户 paladinfeng
> 
> 
> 
> <img width="1084" alt="image" src="https://github.com/Paladinfeng/MiaoProject/assets/15520106/9a15911d-efd8-46b0-ab11-2ab8935f827c">
> 
> 

已添加麻烦通过下，安德森.

**Comment by wjzeng** [comment]
问题已经解决。
