### ISSUE TITLE
希望能够支持https播放

### ISSUE THREAD

**Issue by Dui-Ying** [Paladinfeng/MiaoProject#222]
作者您好，感谢开发这样一款在tvOS上非常好用的B站客户端，不知道后续能否有望支持更加安全的https播放方式？例如在与i0/i1/i2.hdslb.com通信时采用https而非http连接

**Comment by Paladinfeng** [comment]
hdslb.com 这些资源文件的访问都是根据接口来了

目前项目中唯一主动做的 https to http，就是播放链接预解析

**Comment by Paladinfeng** [comment]
并没有特殊处理，都是根据API返回的JSON数据直接请求的
