### ISSUE TITLE
建议将自动调整清晰度的功能做成可设置项

### ISSUE THREAD

**Issue by yxlimo** [Paladinfeng/MiaoProject#27]
感觉这个 feature 挺难做好的，之前用 netflix 的时候体验就很不好。
一来是网速其实是够的，只不过稍微有些波动
二来太糊了也没看头，我宁愿等它加载。

**Comment by Paladinfeng** [comment]
基于原生播放器应该都是采用的HLS的方案
动态分辨率是因为提供了多个分辨率的视频流，自动切换时候的带宽要求是根据API里返回的参数来写的
我自己测试的情况是只出现过一两次降分辨率的情况，而且马上会切回去
目前播放器我认为是做到了比较满意的程度，tvOS 15 之前不会研究这个方案
