### ISSUE TITLE
如何刷新动态，目前好像只能通过杀掉应用重启来看到最新的timeline？

### ISSUE THREAD

**Issue by 361302747** [Paladinfeng/MiaoProject#28]
能不能做成点按刷新

**Comment by Paladinfeng** [comment]
使用前请仔细阅读使用说明，里面写了刷新的机制
要在列表内按刷新键才生效
关于刷新的功能，我目前还没想好，点击上边的Tab刷新可能做不到

**Comment by 361302747** [comment]
好的，感谢大佬回复，原来是暂停播放键刷新。这个有点不符合直觉，所以提的issue。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Paladinfeng/MiaoProject"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 晚上7:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Paladinfeng/MiaoProject] 如何刷新动态，目前好像只能通过杀掉应用重启来看到最新的timeline？ (#28)





 
使用前请仔细阅读使用说明，里面写了刷新的机制
 要在列表内按刷新键才生效
 关于刷新的功能，我目前还没想好，点击上边的Tab刷新可能做不到
