### ISSUE TITLE
追番功能能否实现？

### ISSUE THREAD

**Issue by chingxuds** [Paladinfeng/MiaoProject#29]
跟动态一样，增加一个追番功能区，能够查询已追番剧和当前观看状态。
不知道是否在开发计划中，优先级怎么样。

**Comment by Paladinfeng** [comment]
追番内容正在做

**Comment by chingxuds** [comment]
多谢大佬

**Comment by Paladinfeng** [comment]
不好意思久等了，番剧上线了，请更新 Build 25

**Comment by chingxuds** [comment]
> 不好意思久等了，番剧上线了，请更新 Build 25

多谢大佬，大佬牛逼！
