### ISSUE TITLE
播放器界面触摸板只响应轻击

### ISSUE THREAD

**Issue by frankieyue96** [Paladinfeng/MiaoProject#3]
14.5系统，appletv 4k，播放器界面无法无法下拉，无法按压触控板暂停，非暂停状态下无法划动进度条。

**Comment by hunan128** [comment]
我的也是不能下拉选择，比如关闭弹幕，扬声器选择。

**Comment by Paladinfeng** [comment]
这些都是规划中的功能，还没来得及做呢
