### ISSUE TITLE
playback fails on tvOS 15 public beta 2

### ISSUE THREAD

**Issue by kiracus** [Paladinfeng/MiaoProject#30]
changelog: https://developer.apple.com/documentation/tvos-release-notes/tvos-15-beta-release-notes

**Comment by Paladinfeng** [comment]
- 经测试，tvOS 15 Beta 3 加载视频的过程中不会触发数据回调，可能是新引入的Bug，目前无法修复
- 禁用弹幕之后，也许可以正常播放
- 后续这个问题还要等 Beta 4 测试
