### ISSUE TITLE
直播功能

### ISSUE THREAD

**Issue by yunjianyang** [Paladinfeng/MiaoProject#31]
请问作者打算加入直播功能吗？除此之外有开源的打算吗？我想在你的code上加一加直播功能，如果方便的话。。。

**Comment by Paladinfeng** [comment]
- 直播的问题我有说明过，不确定会不会写，即使写，这个功能也是优先级比较低的
- 目前不打算开源，相关问题我也在 https://www.v2ex.com/t/765455 回复过了
