### ISSUE TITLE
tvOS 15 Beta 3 更新后无法正常播放，持续加载

### ISSUE THREAD

**Issue by littlepanda0716** [Paladinfeng/MiaoProject#33]
自动更新到Build 17后视频列表可刷新，但点进视频播放后持续显示加载画面。

系统版本： tvOS 15.0 developer beta 3
设备： Apple TV 4K（第1代）

**Comment by Paladinfeng** [comment]
- Beta 3 会导致某些情况下，播放请求无数据回调，设置里关闭弹幕之后就可以播
- 不建议任何普通用户更新 Beta 系统

**Comment by littlepanda0716** [comment]
关闭弹幕后成功打开视频，感谢🙏

**Comment by Hotinosin** [comment]
进视频播放后持续显示加载画面，返回键无效，只能回桌面

系统版本： tvOS 15.0 developer beta 3
设备： Apple TV 4K（第2代）

**Comment by Paladinfeng** [comment]
Beta 4 更新之后，出现了关掉视频之后，声音还是继续播放的问题

**Comment by littlepanda0716** [comment]
Beta4 播放过程中会遇到自动退出播放的情况，退出后返回到视频详情页

**Comment by Paladinfeng** [comment]
> Beta4 播放过程中会遇到自动退出播放的情况，退出后返回到视频详情页

可能是播放过程中出错了，现在设置catch到error，直接退出，能提供一下是哪个视频吗？

**Comment by littlepanda0716** [comment]
【这是什么神仙广告??? - Apple AirPods Pro-哔哩哔哩】https://b23.tv/oBeR6v

目前有遇到多个不同视频都存在视频自动退出，且退出时已播放时长不同，apple tv重启后播放同视频没能在相同时刻复现退出播放。

ZFXUE ***@***.***>于2021年7月29日 周四下午10:21写道：

**Comment by littlepanda0716** [comment]
tvOS 15 beta 4 中遇到点击搜索中的“查看全部”无响应情况

**Comment by littlepanda0716** [comment]
> > Beta4 播放过程中会遇到自动退出播放的情况，退出后返回到视频详情页
> 
> 
> 
> 可能是播放过程中出错了，现在设置catch到error，直接退出，能提供一下是哪个视频吗？

Beta 5 中退出视频后继续播放声音的bug已修复。视频闪退和弹幕打开后无法加载的bug暂未测试

**Comment by Paladinfeng** [comment]
- Beta 5 还是无法加载弹幕，暂时没发现其他问题

**Comment by yangdelu855** [comment]
蹲 beta5支持弹幕

**Comment by QuietXxX** [comment]
更新了遇到这情况😭

**Comment by littlepanda0716** [comment]
> - Beta 5 还是无法加载弹幕，暂时没发现其他问题

Beta5中搜索页面点击查看全部也无响应

**Comment by Paladinfeng** [comment]
> > * Beta 5 还是无法加载弹幕，暂时没发现其他问题
> 
> Beta5中搜索页面点击查看全部也无响应

这功能还没做呢

**Comment by mtunique** [comment]
求fix 弹幕

**Comment by Paladinfeng** [comment]
> 求fix 弹幕

这是一个系统 Bug，但是不清楚苹果会不会修复，相关问题我已经提交上去了，如果正式版发布之前还是没有修复，我会采用备用方案

**Comment by QuietXxX** [comment]
Beta 6还不能用😭😭
