### ISSUE TITLE
默认4K情况下缓慢掉帧

### ISSUE THREAD

**Issue by Turingmachine01** [Paladinfeng/MiaoProject#34]
设置为4K分辨率后视频一开始很流畅，然后逐渐掉帧变卡，并不是网络导致的一卡一卡的感觉，就是帧率不够的情况。换成1080p60帧后问题消失

**Comment by Paladinfeng** [comment]
首选确实一下你现在的build版本有没有更新，如果更新到最新版了，麻烦发一个录屏给我
