### ISSUE TITLE
可否增加个连播功能

### ISSUE THREAD

**Issue by guohaomiao** [Paladinfeng/MiaoProject#36]
大佬 可否给番剧增加个连播功能，适合一口气看完很多集：）

**Comment by Paladinfeng** [comment]
之后会和自动播放下一P的功能一直做

**Comment by guohaomiao** [comment]
嗯嗯 感谢大佬 再有联播就完美了 ：）

**Comment by internelp** [comment]
赞同，毕竟是电视客户端，就应该是只有用户不手动停止就一直播放。

**Comment by PerpEternal** [comment]
会增加续播的功能吗？现在每次点播放都是从第一话开始播放

**Comment by Paladinfeng** [comment]
Build 54 已更新

**Comment by guohaomiao** [comment]
感谢大佬，目前还没收到更新，明天晚上研究下。ps 能从程序内部看到版本号吗？

**Comment by PerpEternal** [comment]
> 

番剧不能根据观看记录续播吗，每次点播放都是从第一话开始播放，或者是否能够倒序排列选集，不然每次看新的一话都要翻很久

**Comment by Paladinfeng** [comment]
1. 直接点播放，那就从第一集开始播
2. 如果番剧大于50集，会出现展开全部的按钮

> > 
> 
> 番剧不能根据观看记录续播吗，每次点播放都是从第一话开始播放，或者是否能够倒序排列选集，不然每次看新的一话都要翻很久

**Comment by guohaomiao** [comment]
十分感谢。才发现我也被大佬从测试名单里移除了，难怪没收到build。大佬如果还有名额就求个邀请邮件。没有的话就算了 我月底盯着点 3Q
ZFXUE ***@***.***> 于2022年1月19日周三 18:09写道：

**Comment by Paladinfeng** [comment]
目前满载了，预计月底重新开放

**Comment by guohaomiao** [comment]
明白 猫着月底了：）

**Comment by guohaomiao** [comment]
已get到build 反馈个问题（在我来看其实不是问题） 就是弹幕的开关功能在连播状态下是失效的，无论怎么设置，都会在播放下一集时加载弹幕 ：）

**Comment by Paladinfeng** [comment]
下版本修复
> 已get到build 反馈个问题（在我来看其实不是问题） 就是弹幕的开关功能在连播状态下是失效的，无论怎么设置，都会在播放下一集时加载弹幕 ：）

**Comment by guohaomiao** [comment]
老大 最近还发现个问题，番剧连播的时候，视频时长获取不正确。举个例子 蜡笔小新第5季第60集 从手机app上获取的是09:24，但是app在09:02进入切换视图，所以就算加上联播倒计时10s还是差了12s的视频片尾。在很多片尾曲后有内容的动画都会存在这个问题。

**Comment by Paladinfeng** [comment]
目前会在结束前的20s提示切换下一集，然后倒计时10s后自动播放
目前不能获取精确的ED时间，所以只能固定一个时间

**Comment by PerpEternal** [comment]
> 1. 直接点播放，那就从第一集开始播
> 2. 如果番剧大于50集，会出现展开全部的按钮
> 
> > > 
> > 
> > 
> > 番剧不能根据观看记录续播吗，每次点播放都是从第一话开始播放，或者是否能够倒序排列选集，不然每次看新的一话都要翻很久

能把50这个阈值调小一点吗？每次翻到最后有点累
