### ISSUE TITLE
是不是不支持互动功能的视频，罗老师的视频打不开

### ISSUE THREAD

**Issue by jliu666** [Paladinfeng/MiaoProject#37]

**Comment by Paladinfeng** [comment]
不支持，近期也不会做这个需求，互动视频没仔细研究，在 tvOS 上的交互和视频片段的切换都比较麻烦

**Comment by jliu666** [comment]
我的意思是这个视频能不能打开，难道是b站的私有格式，不是正常的视频内容

**Comment by Paladinfeng** [comment]
互动视频不是一个独立的视频，调用的接口也是和普通视频不一样的，需要根据用户选择，播放出来的多个视频，互动视频需要解决用户选择以及交互的问题
