### ISSUE TITLE
字幕现在有吗

### ISSUE THREAD

**Issue by wzh4464** [Paladinfeng/MiaoProject#38]
我看md里面写有，但是我追番里面的字母没有啊，港澳台番剧那种

**Comment by Paladinfeng** [comment]
现在已经可以支持外挂字幕了，可能需要你手动选择一下，可以在播放的时候下滑呼出字幕菜单，然后选择语言
https://support.apple.com/zh-cn/guide/tv/atvb7944597f/14.0/tvos/14.0

**Comment by Paladinfeng** [comment]
如果还是有问题，请提供一下番剧名称，我去测试一下
