### ISSUE TITLE
请问APP访问的域名是bilibili.com吗？

### ISSUE THREAD

**Issue by dreamUshuaia** [Paladinfeng/MiaoProject#41]
谢谢开发者。
请问APP访问的域名是bilibili.com吗？
用的路由器刷梅林固件翻墙，所以有的时候会把APP送到HK，所以想设置一下白名单

**Comment by Paladinfeng** [comment]
以下是目前涉及到的全部域名

"https://app.bilibili.com/"
"https://api.bilibili.com/"
"https://passport.snm0516.aisee.tv/"
"https://api.vc.bilibili.com/"
"https://bangumi.bilibili.com/"
