### ISSUE TITLE
偶尔热门和推荐里有互动视频，互动视频可否考虑加个标记

### ISSUE THREAD

**Issue by blackisle** [Paladinfeng/MiaoProject#42]
B站互动视频 AppleTV OS支持不了可以理解，可否在误点互动视频时给点提示或者标记下视频为互动视频吗？最初使用刚好碰到推荐视频连续两个都是互动视频，还以为遥控器坏掉了。不麻烦的话可否考虑给个提示或者加个互动视频标记？纯属个人使用感触，善意探讨冒犯之处请见谅

**Comment by Paladinfeng** [comment]
这个问题我再研究一下接口，目前接口返回的数据里没发现那个字段是表示「互动视频」的，当时的互动视频不能播放单纯是因为数据结构中缺少 aid
