### ISSUE TITLE
现在番剧的选集模式对长篇不太友好

### ISSUE THREAD

**Issue by Fengzly** [Paladinfeng/MiaoProject#51]
柯南1000多集划到手快断了😂能不能像原来b站原生安卓tv客户端一样 超过100话的番剧 每100话分个组 选了分组再选集数这样？

**Comment by Paladinfeng** [comment]
抱歉带来了不好的体验，这个问题会改进的，更新之前还是暂时放弃这种超长番剧吧

**Comment by Paladinfeng** [comment]
更新 Build 30
