### ISSUE TITLE
程序无法正常工作

### ISSUE THREAD

**Issue by guohaomiao** [Paladinfeng/MiaoProject#53]
程序无法正常工作，b站的tv登录api似乎变了，无法请求到二维码，已有的token似乎也失效了。楼主要不要考虑下用web的登录方式？

**Comment by Paladinfeng** [comment]
tvOS 是不支持 Web 的，为啥你自己关了 issue？问题解决了？

**Comment by guohaomiao** [comment]
实属抱歉，是我的路由死机了。。。 华硕的aimesh可靠度真的不高。。。 子节点死掉了完全没有征兆 :(( 其他设备通过wifi动态切换到了住路由，atv和另一个设备是用线路连接到的子路由，所以根据错误信息误以为b站封锁了相关接口 :(( 。上面的意思是改用网页登录方式的接口获取token，因为不知道b站这个tv版能活多久:(
