### ISSUE TITLE
收藏夹不兼容 番剧/电影 类型的视频

### ISSUE THREAD

**Issue by yxlimo** [Paladinfeng/MiaoProject#57]
- 在番剧/电影的详情页无法加入收藏夹
- 已加入收藏夹的番剧/电影不显示

期望
- 能从收藏夹里跳转到番剧/电影 （P0）
- 在番剧/电影的详情页能够将其加入收藏夹（P1）

**Comment by Paladinfeng** [comment]
收藏夹接口已更新
