### ISSUE TITLE
有计划支持直播吗

### ISSUE THREAD

**Issue by irobbin1024** [Paladinfeng/MiaoProject#59]
如标题所示

使用b站比较多的是直播功能，不知道作者近期有没有计划支持呢

**Comment by Paladinfeng** [comment]
直播的技术方案，除了弹幕之外，已经调研完毕，但是目前仍然在设计阶段，短时间内不会支持

**Comment by irobbin1024** [comment]
我研究了下b站的API，可以拿到直播地址，通过mac上的iina播放器可以播放，应该是一个flv的直播方案，但是没有找到开源的支持flv的方案，不知道你是自己写的还是采用的开源方案，能否告知一下呢

**Comment by Paladinfeng** [comment]
官方有一个API是可以直接获取m3u8的地址，可以直接播放
可以参考这个项目：https://github.com/yichengchen/ATV-Bilibili-live-demo
