### ISSUE TITLE
考虑加个倍速吗？

### ISSUE THREAD

**Issue by Sh7ne** [Paladinfeng/MiaoProject#60]
如题，没有倍速长视频很难下饭啊。

另外好几百番的视频进去之后各个p完全横向排列。。。。基本上不可用了。。。

**Comment by Paladinfeng** [comment]
- 倍速播放仅支持 tvOS 15 了，但是可能会卡顿，原因未知
- 超长番剧暂时先放弃吧，没想好怎么优化
