### ISSUE TITLE
Build 30无法正常使用

### ISSUE THREAD

**Issue by raiuka** [Paladinfeng/MiaoProject#63]
Apple TV 6代，tvOS 15，MiaoProject版本Build 30，点击任何视频播放都会退回桌面，尝试过重新安装，重新登录均无法解决。。。。

不知道该提供什么样的信息。。

**Comment by Paladinfeng** [comment]
目前没收到类似的反馈，我本地测试也没有出现类似情况
你在TG群里吗？在的话可以私聊我一下

**Comment by raiuka** [comment]
> 目前没收到类似的反馈，我本地测试也没有出现类似情况
> 你在TG群里吗？在的话可以私聊我一下

我加群，然后私聊找你。。。
