### ISSUE TITLE
使用代理后无法观看

### ISSUE THREAD

**Issue by Ahaxzh** [Paladinfeng/MiaoProject#69]
问题描述：
Mac 上Surge 做网关 Apple TV上使用Miao Project的时候可以打开查看榜单列表等所有内容，但是无法播放。

Surge非全局代理，使用配置规则。

**Comment by Paladinfeng** [comment]
这要看你自己的配置了，如果你用了去广告的规则的话，也可能是误杀了，这要你自己去调试一下了
