### ISSUE TITLE
视频加载卡住

### ISSUE THREAD

**Issue by lipancs** [Paladinfeng/MiaoProject#71]
经常观看若看个视频以后，打开新的视频会随机出现转圈等待，程序无响应。只有退出到主界面划掉，重新再进

**Comment by Paladinfeng** [comment]
这很多时候都是和网络状态有关系，可能你有问题，但是我这里却没问题

如果是某个视频稳定复现问题的话，请提供一下视频ID，否则我也没法 Debug
