### ISSUE TITLE
番剧列表加载失败

### ISSUE THREAD

**Issue by haipiao** [Paladinfeng/MiaoProject#74]
账号登陆状态下，追番列表以及番剧列表内的视频无法加载出来，多次重启后偶尔有一次可以恢复正常，看一到两个视频后就又无法加载视频列表，apple tv登陆网络有翻墙，但是有大陆白名单规则

**Comment by haipiao** [comment]
以上情况目前只针对番剧列表，其他视频暂无无法加载播放情况出现

**Comment by Paladinfeng** [comment]
- 测试了一下，我本地是可以正常加载的
- 你可以关闭本地的所有代理/去广告插件，再试一下，或者连手机热点测试一下
- 目前的情况，估计是你的网络问题，可能会规则误杀或者走了代理
