### ISSUE TITLE
是否可能增加投屏功能？

### ISSUE THREAD

**Issue by jdjingdian** [Paladinfeng/MiaoProject#77]
大佬好，有的时候我在手机上看到一个视频想投到电视上看，B站把airplay投屏的方式限制在720p看着很不舒服，官方投屏页面显示必须是云视听小电视才能投高清的，不知道大佬的客户端未来是否可能从手机端投屏呢？
另外谢谢大佬，您的应用真的好用，感激！

**Comment by Paladinfeng** [comment]
抱歉，这不是一个第三方应用可以做到的
如果你想在电视上观看，最简单的做法是用历史记录或者稍后再看的功能
