### ISSUE TITLE
倍速播放问题

### ISSUE THREAD

**Issue by mlch911** [Paladinfeng/MiaoProject#78]
倍速播放时，暂停再播放，倍速就会失效，但倍速选项那儿还显示开着倍速播放。

**Comment by Paladinfeng** [comment]
- 倍速播放的时候确实有这个问题，除此之外，倍速播放还可能导致视频掉帧，目前没找到好的解决办法
- 暂停之后，播放器的速率变成0，继续播放会变成1，而原来可能是1.5
- 这个问题我之后会修，但是倍速播放掉帧导致这个功能还是不太好用🤣

**Comment by mlch911** [comment]
掉帧无所谓，反正都是倍速了。只要能保持倍速就行。另外，退出播放界面的黑屏时间有点久

**Comment by CyEilo** [comment]
> 掉帧无所谓，反正都是倍速了。只要能保持倍速就行。另外，退出播放界面的黑屏时间有点久

我不会黑屏 你看下是不是atv里面开启了同步帧速率和同步动态范围导致的

**Comment by mlch911** [comment]
> > 掉帧无所谓，反正都是倍速了。只要能保持倍速就行。另外，退出播放界面的黑屏时间有点久
> 
> 我不会黑屏 你看下是不是atv里面开启了同步帧速率和同步动态范围导致的

嗯嗯，确实是这两导致的，好像也没啥解决方法，很烦🤣

**Comment by Paladinfeng** [comment]
最新版本已增加为实验室功能，开启全局倍速，可能导致部分UGC视频丢帧
