### ISSUE TITLE
关于视频下方“推荐视频”的返回逻辑

### ISSUE THREAD

**Issue by collinyea** [Paladinfeng/MiaoProject#79]
和官方APP不同的是，访问每个视频下方的“推荐视频”，每次不是返回至上一个视频，而是直接回退到最外层分类。如果确实是这么设计的话，能否增加一个选项，改变返回方式？

**Comment by Paladinfeng** [comment]
- 设计上我是想点击之后，直接刷新当前页面到新视频的，官方客户端的逻辑也是这样
- 如果每次都打开一个新页面的话，一个是会占用更多内存，另一个是返回的时候只能一层一层退出，如果进入的层级比较深，那可能退出会比较烦
- 如果需要的人多，那我可以增加一个相关的设置

**Comment by CyEilo** [comment]
原来已经有人提过了 , 给个建议不知道合不合理
做个队列 只保存链接 不保留页面 同时限制最大条目 (正常情况下类似我和Author的使用场景下需要返回的层数不会超过五层)

**Comment by polaire** [comment]
确实是有这个问题，希望能够逐级返回而不是一次性地退出到首页视频列表。其实在B站很多时候闲逛都是看到一个视频A点进去，看完后下面的推荐列表里面有类似内容的推荐，可能有好几个视频（B、C、D）都是感兴趣的，于是就先进入视频B，看完后再点击返回回到A的页面，通过下面的推荐列表继续看C；之后再返回看D……但是目前的设置是看完B之后点击返回不是返回A的页面而是直接回到根目录了，这样为了继续看C和D还需要首先找到A的页面，而有可能已经都忘了当时是如何看到A的了。

所以，鉴于以上使用场景，还是希望能够按照官方App的逻辑设置这个返回的机制，请大神酌情考虑。

**Comment by Paladinfeng** [comment]
之后会加一个逐级返回的开关，不过我最近在写多用户系统，要稍微等等

**Comment by Paladinfeng** [comment]
已更新设置，相关推荐视频弹出新页面，不过没有加入层级的限制
