### ISSUE TITLE
希望支持登录/切换多个账户

### ISSUE THREAD

**Issue by ntzyz** [Paladinfeng/MiaoProject#8]
考虑到电视机往往不是一个人独自使用，感觉多用户有必要支持一下，类似 Netflix/Plex 那种交互，如果支持 pin 码验证就更好了

**Comment by Paladinfeng** [comment]
多用户支持的逻辑比较复杂，目前基本功能还有部分要补，短期之内不会实现

**Comment by ntzyz** [comment]
如果以 AppleTV 自身的多用户切换为切入点，实现类似的效果会简单一点吗？比较好奇

**Comment by jcc563768606** [comment]
希望能直接支持用appletv的账号切换来切换b站账号

**Comment by Paladinfeng** [comment]
多账户功能已更新
