### ISSUE TITLE
无法激活电视的杜比视界模式

### ISSUE THREAD

**Issue by PerpEternal** [Paladinfeng/MiaoProject#80]
播发杜比视界片源时只能激发电视的HDR10模式，无法激发杜比视界模式
电视：Sony x90j
![A6B67F85-60B7-44FC-9779-4BA7EDE7AEFC](https://user-images.githubusercontent.com/30803659/146017975-896ed445-2b2d-4315-bee9-b146d1c130ed.jpeg)

**Comment by Paladinfeng** [comment]
- 更新之后的使用说明里有写
- https://github.com/Paladinfeng/MiaoProject/blob/master/HOW-TO-USE.md
