### ISSUE TITLE
关于Build 51收藏夹的问题

### ISSUE THREAD

**Issue by GiovanniVDW** [Paladinfeng/MiaoProject#81]
首先要感谢一下大佬的贡献！发现一个问题：Build 51更新后，“我创建的收藏夹”目录超过20个的部分，一直向右划动也无法加载显示了，麻烦看看是哪部分的问题，谢谢。

另外提一个小小的建议，收藏夹界面能否设计为多行的效果，收藏夹较多的情况下，单行滚动操作较为麻烦。

**Comment by Paladinfeng** [comment]
收藏列表出了一些 Bug，本来超过 20 个应该显示「查看全部」的按钮的

下版本修复这个问题

**Comment by GiovanniVDW** [comment]
感谢大佬回复，辛苦了！
