### ISSUE TITLE
番剧无法全屏播放

### ISSUE THREAD

**Issue by Ericjt11** [Paladinfeng/MiaoProject#85]
柯南中配版无法全屏，原声版可以，什么原因导致呢，找了下好像没有相关设置

**Comment by Paladinfeng** [comment]
具体是哪一集呢？还有无法全屏是什么意思？

**Comment by Ericjt11** [comment]
659话前后，就是四边有等宽黑边，画面居中。刚又看了下前面4：3的可以全屏，新出的最新话也可以。

**Comment by Ericjt11** [comment]
![image](https://user-images.githubusercontent.com/60682946/146955667-7ea5ef11-7921-4304-8187-e1f0378fd5a0.jpeg)

**Comment by Paladinfeng** [comment]
去官网看了一下，原视频就这样，另外，Apple TV 连续点两下触摸板可以改为按宽度对齐

**Comment by Ericjt11** [comment]
好吧怪我没先去核实，感谢回复
