### ISSUE TITLE
排行榜中的游戏分类实际上是舞蹈分类

### ISSUE THREAD

**Issue by KyleRicardo** [Paladinfeng/MiaoProject#86]
如题，游戏分类实际上缺失，实际内容是舞蹈相关内容（而且与舞蹈分类的内容一致），不知是不是链接出问题了。

**Comment by Paladinfeng** [comment]
可能只是没刷新出来数据？重启应用试过吗？我这边目前是正常的

![1](https://user-images.githubusercontent.com/15520106/147175514-46b51563-aadc-42eb-b5a3-34d4f98d3a9c.png)

**Comment by KyleRicardo** [comment]
今天我重启试了下，发现正常了，可能是偶发bug？由于不确定能复现，我先关闭issue了。
