### ISSUE TITLE
apple tv hd 只能支持1080播放，但自适应感觉都能到4k

### ISSUE THREAD

**Issue by chenfengfeng** [Paladinfeng/MiaoProject#87]
有些视频会根据网速达到4k，这样老型号解析就变得很卡，能否在设置多一个最高画质限制

**Comment by Paladinfeng** [comment]
1. 现在确实是限制了Apple TV HD的分辨率，理论上来说不会把分辨率拉到1080P以上了，不过我手边没有实际的设备可以测试
2. 如果正在加载4K的视频流，视频播放的时候，简介里应该会亮4K的标志
3. 如果你有Mac，可以打开开发者模式，看一下详细参数的截图，方法如下：https://www.howtogeek.com/409201/how-to-unlock-detailed-streaming-statistics-on-the-apple-tv/

**Comment by chenfengfeng** [comment]
@Paladinfeng 
查看了下，拿8k的视频来播放，最高也应该是1080
所以还是机能问题，导致播放着就卡了，特别是开了弹幕。。
![Screen Shot 2021-12-25 at 00 23 23](https://user-images.githubusercontent.com/6957977/147364574-21fd0a9d-34fa-4333-a7b6-b4ea9f98b2d4.png)

**Comment by Paladinfeng** [comment]
你是不是开了「优先加载HEVC」？
如果是 Apple TV HD 的话，建议关掉这个选项，因为硬件不支持硬解 HEVC

**Comment by chenfengfeng** [comment]
@Paladinfeng 我去，你提醒我了，我看了真的开着，hd还不支持265硬解，关掉后感觉流畅了很多～
