### ISSUE TITLE
多加点内测名额吧

### ISSUE THREAD

**Issue by zhuhuayu1998** [Paladinfeng/MiaoProject#88]
大神麻烦多加点内测名额，求求了

**Comment by Paladinfeng** [comment]
当前测试已经满载，邀请链接已停用，预计月底有名额释放出来

**Comment by qq251347273** [comment]
请求加名额

**Comment by zhuhuayu1998** [comment]
> 

好的，感谢回复

**Comment by polaire** [comment]
同样，请求增加名额~ 需要付费也行。。。

**Comment by bighead521** [comment]
支持付费，快快开放吧~

**Comment by 1345683654** [comment]
支持付费使用，求开放名额和TG群的入口呀

**Comment by Paladinfeng** [comment]
TG群在首页，预计月底重新开放

**Comment by 1345683654** [comment]
> 

好的好的，多谢，期待月底的增加了

**Comment by Paladinfeng** [comment]
新年快乐，Miao Project 已重新开放测试，GitHub上的测试邀请链接不变，刚刚有大量使用Build 36 的旧用户过期，如果需要继续使用，请重新加入，感谢各位的参与🤣

**Comment by 1345683654** [comment]
感谢提醒，已安装





------------------ 原始邮件 ------------------
发件人: ZFXUE ***@***.***&gt;
发送时间: 2022年1月31日 14:15
收件人: Paladinfeng/MiaoProject ***@***.***&gt;
抄送: 1345683654 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Paladinfeng/MiaoProject] 多加点内测名额吧 (Issue #88)





 
新年快乐，Miao Project 已重新开放测试，GitHub上的测试邀请链接不变，刚刚有大量使用Build 36 的旧用户过期，如果需要继续使用，请重新加入，感谢各位的参与🤣
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
