### ISSUE TITLE
连续点击视频下方相关推荐 有概率出现:开始播放的时候卡死

### ISSUE THREAD

**Issue by CyEilo** [Paladinfeng/MiaoProject#89]
build 53 
Apple TV 4k 2017
Apple TV 4k 2021 
看视频A后 点击下方推荐视频B 看了B之后再B下方的推荐视频C 连续操作多次之后 
有概率出现打开某个视频时 一直转圈加载 点击返回键无反应 
此时点击home键到Apple tv主页后 再次打开app会闪退,再次打开app重启可正常使用

BTW 目前按照上面的操作 假设B下方有相关推荐C和D,打开视频C后按返回键会直接回到app首页 而不是回到B的页面 如果这时候我想看完C再看D的话找起来会比较麻烦,
能否针对类似的操作保留2-4层可以返回的机会

谢谢你的贡献

**Comment by Paladinfeng** [comment]
1. 已更新设置，相关推荐视频弹出新页面，不过没有加入层级的限制
2. 视频卡死未能复现
