### ISSUE TITLE
4K分辨率下部分视频播放时掉帧

### ISSUE THREAD

**Issue by tsukijohn** [Paladinfeng/MiaoProject#91]
版本：1.0 (53)
硬件：Apple TV 4K 2017
系统：tvOS 15.2

问题：
1. 在4K分辨率下（包括杜比视界、HDR、SDR），部分视频播放二十秒左右会开始掉帧，逐渐音画不同步
2. 以下方式可以使掉帧情况恢复正常，但随后问题依旧：
    (1) 暂停播放：声音暂停，画面继续，直至音画同步
    (2) 触摸遥控器唤出播放菜单，画面加速播放直至音画同步
3. 掉帧现象与视频分辨率无关，但与电视分辨率有关。1080P及以下分辨率没有掉帧情况出现
4. 掉帧情况不受APP设置影响

示例视频链接：https://www.bilibili.com/video/BV1RS4y1j7mR

补充内容：
1. 账号已开通大会员

**Comment by Paladinfeng** [comment]
这个问题的根本原因是，目前项目使用的AVPlayer播放器是不支持60帧以上的帧数的，一旦视频超过60帧，就会出现掉帧的问题

打开下边两项设置可能会改善掉帧问题
1. 关闭设置中的仅加载最高分辨率
2. 开启系统设置中的匹配帧率和匹配动态范围

**Comment by tsukijohn** [comment]
> 这个问题的根本原因是，目前项目使用的AVPlayer播放器是不支持60帧以上的帧数的，一旦视频超过60帧，就会出现掉帧的问题
> 
> 打开下边两项设置可能会改善掉帧问题
> 
> 1. 关闭设置中的仅加载最高分辨率
> 2. 开启系统设置中的匹配帧率和匹配动态范围

确实是视频超过60帧时出现这种情况。不过这两种方式都试过，没有解决问题。

**Comment by kamenriderzxt** [comment]
我电视是1080的，在可以自己选择分辨率版本的时候不会掉帧，我不知道什么时候自动更新到了自动分辨率版本，现在看着看着有掉帧的情况，暂停再播放可以解决一会儿。尝试过设置里的各种关于视频播放的设置，什么仅加载最高分辨率之类的选项，怎么调试都没用，看着看着就会掉帧，需要暂停再播放，过一会儿又掉帧，又要再来一次。表示很难受。有大会员。

**Comment by Paladinfeng** [comment]
Build 63 更新了一个设置 -「过滤超过60帧的视频」，卡顿掉帧的，试一下开启之后还有没有问题
- 新增：设置 -「过滤超过60帧的视频」，开启后可能会改善某些视频丢帧导致无法正常观看的问题，请仔细阅读说明和副作用，仅建议有此问题的用户自行尝试
