### ISSUE TITLE
测试名额被回收了。

### ISSUE THREAD

**Issue by Mtrestm** [Paladinfeng/MiaoProject#92]
太突然了，下午还在用 刚刚发现我的名额被回收了。 愿意付费支持作者，期待有新的公告出来。等~

**Comment by Mtrestm** [comment]
打工人。最开心的一件事之一就是周末连着投影仪用appletv 刷B站 😀  希望能争取回来名额Mtrestm@outlook.com

**Comment by Paladinfeng** [comment]
估计你不太关注项目相关的消息

这次被移除测试是在几个月前的一次，那次清空了全部测试用户，但是直到现在，才真正的移除生效

当前测试已经满载，暂时无法重新加入了，预计月底有名额释放出来，到时候会在TG群中通知的

**Comment by Mtrestm** [comment]
好的，好的。下电报，加群关注😁

**Comment by Mtrestm** [comment]
也挺想学习这个软件怎么制作的 太厉害了。

**Comment by xinxinoooo** [comment]
> 估计你不太关注项目相关的消息
> 
> 这次被移除测试是在几个月前的一次，那次清空了全部测试用户，但是直到现在，才真正的移除生效
> 
> 当前测试已经满载，暂时无法重新加入了，预计月底有名额释放出来，到时候会在TG群中通知的

问一下 怎么加群呢？

**Comment by polaire** [comment]
同问，怎么加群呀？不想错过下次发放名额~

**Comment by polaire** [comment]
眼看就月底了。。。每天都上来刷好几次，眼巴巴等着。。。。

**Comment by Paladinfeng** [comment]
> 眼看就月底了。。。每天都上来刷好几次，眼巴巴等着。。。。

久等了，不需要每天都刷的，重新开放之后，我会回复并关闭这个issue的

**Comment by polaire** [comment]
> > 眼看就月底了。。。每天都上来刷好几次，眼巴巴等着。。。。
> 
> 
> 
> 久等了，不需要每天都刷的，重新开放之后，我会回复并关闭这个issue的

嗯嗯，就是怕错过通知又抢不上名额呀～ 等大神的回复啦那就

**Comment by polaire** [comment]
月底还剩两天。。。。大神加油……好希望能够在春节用上啊……

**Comment by fankai1019** [comment]
求增加测试名额

**Comment by Paladinfeng** [comment]
新年快乐，Miao Project 已重新开放测试，GitHub上的测试邀请链接不变，刚刚有大量使用Build 36 的旧用户过期，如果需要继续使用，请重新加入，感谢各位的参与🤣
