### ISSUE TITLE
祝大神和各位春节快乐！

### ISSUE THREAD

**Issue by polaire** [Paladinfeng/MiaoProject#98]
春节快乐，阖家幸福，万事如意！

等待开放测试名额中。。。

**Comment by Paladinfeng** [comment]
新年快乐，Miao Project 已重新开放测试，GitHub上的测试邀请链接不变，刚刚有大量使用Build 36 的旧用户过期，如果需要继续使用，请重新加入，感谢各位的参与🤣

**Comment by polaire** [comment]
赞！终于等到了，已经申请～～多谢🙏
